### ISSUE TITLE
unexpected poorer accuracy on truncated files?

### ISSUE THREAD

**Issue by thealk** [MontrealCorpusTools/Montreal-Forced-Aligner#103]
I did a quick and dirty first pass of training and alignment (mfa_train_and_align) on a bunch of short .wav files (usually 2-20 seconds) that hadn't been truncated and in some cases contained additional speech compared to what was transcribed. The aligner still did quite well on these files, even in the case of unexpected speech/long silences.

I have since truncated the files so they only contain about 50ms of silence at either end of the utterance, and the transcripts match exactly. Rerunning the aligner, it does not seem to do as well (phone-level alignment is not as accurate as it was in the first pass). I am wondering if 1) this is because it expects more silence at the beginning than I am providing, and/or 2) if modifying the boost_silence parameter in a provided config file is an appropriate possible solution (in which case, what would be an appropriate value?).

Possibly also relevant is that all utterances begin with a plosive /p/, so perhaps it's trying to model longer closure than is present at the beginning of the file. 

In both cases I aligned with:

- mfa_train_and_align (training on self)
- -s prosodylab (70 speakers, each with ~ 104 files)
- custom dictionary with words of interested added

Attached are two screenshots of an example file. 

The first is prior to truncation (no extra speech in this example, though wav/transcript do contain an additional word which was cut after truncation). 

The second is following truncation. The highlighted /f/ is longer and catches more of the following vowel in the truncated example. The first word "please" also doesn't accurately catch the whole VOT (maybe because it expects more initial silence). I'm not so concerned with the beginning of the utterances, as the words of interest are all in the middle, and in my past experience with mfa the alignment catches up quite well, but perhaps this is part of the problem.

**untruncated:**
![untruncated](https://user-images.githubusercontent.com/3257971/53252144-4146ef80-368c-11e9-911f-50d75d4ede11.png)

**truncated:**
![truncated](https://user-images.githubusercontent.com/3257971/53252189-56238300-368c-11e9-8a53-1b7bbd47cc25.png)

**Comment by mmcauliffe** [comment]
So I think the main issue is using `mfa_train_and_align` instead of `mfa_align` with a model trained on much more data.  I've noticed also that aligning on just lab data with very formulaic transcriptions (i.e., all of the form "please say X again") leads to poor training in particular, whereas training on experiments with more natural sentences does better.  

There should be enough data in terms of time, I think (~6 hours of speech using the untruncated one as the the length of all files), but the formulaic nature makes it very hard to learn.  My guess is something about the initialization being uniform and then it gets stuck in a local minimum because the sentences share so much phonetic information in that particular order.

**Comment by thealk** [comment]
Ah okay, that makes sense as to why it would have oddly done better on the messier (but more variable) first attempts. Also useful to know as there are multiple target rates of speech for these data as well, and I'd also tried splitting the data into slow vs fast to see if that would help (it made it worse, which would also be explained by what you're describing). Thanks!
