### ISSUE TITLE
Only 1172 out of 11694 TextGrid files are generated

### ISSUE THREAD

**Issue by danielkorzekwa** [MontrealCorpusTools/Montreal-Forced-Aligner#120]
version: 1.0.1, macos

When calling mfa_align script on the input directory with wav and lab files, only 1172 TextGrid files out of 11694 wav files are generated.

Every wav file is a single word from the LDC93S1/test corpus, for example: test_DR4_MLLL0_SA1_year.wav

There are 8 speakers DR1... to DR8 (however, because all files are in the single directory, then for the mfa_align, there is just one speaker with 11694 files.

There are just two oov.

Using the flag '-s prosodylab' forces mfa_align to recognize all 8 speakers and then somehow 2899 out of 11694 TextGrid files are generated.

Running mfa_align for a different wav database with about 10K wav files, generates all TextGrid files. However, file naming convention is different, e.g. 41_port.wav (NUMBER_WORDNAME.wav)

**Comment by thepowerfuldeez** [comment]
hey! i have the same problem

**Comment by mmcauliffe** [comment]
@thepowerfuldeez I think you should make a new issue with details on your issue. I'm going to close this one, since it's fairly old and is likely related to the specific data format (looks like TIMIT split somehow into individual words, but that doesn't really make much sense from an alignment standpoint, since it expects multi word utterances bounded by silence on both ends).
