### ISSUE TITLE
Division by Zero error

### ISSUE THREAD

**Issue by adfost** [MontrealCorpusTools/Montreal-Forced-Aligner#164]
Traceback (most recent call last):
  File "aligner/command_line/align.py", line 186, in <module>
  File "aligner/command_line/align.py", line 142, in validate_args
  File "aligner/command_line/align.py", line 85, in align_corpus
  File "aligner/corpus.py", line 543, in speaker_utterance_info
ZeroDivisionError: division by zero

This is the error I get when I try to run aligner on a folder in the LibriSpeech dataset, with one file augmented to the dataset. I converted everything to wav file.

**Comment by adfost** [comment]
./montreal-forced-aligner/bin/mfa_align ./130880 ./montreal-forced-aligner/pretrained_models/librispeech-lexicon.txt ./montreal-forced-aligner/pretrained_models/english.zip ./TextGrids

**Comment by sandcobainer** [comment]
Any update on this or how you solved this? @adfost

**Comment by mmcauliffe** [comment]
The root issue is that sound file/transcription files are not found.  I've updated the error message to be more helpful.

**Comment by halannhile** [comment]
some things that helped me fix this error: 

1. make sure whenever you rerun the "mfa validate" or "mfa align" commands from the same folder where you have made changes to the TextGrid or .wav files, e.g. "c:/asr_project/speech_corpus", you need to first delete the folder with the same name in the MFA's source location on your computer, for me, it is "C:\Users\user_name\Documents\MFA\speech_corpus". otherwise, I find that "mfa validate" and "mfa align" will still reference the old data in your folder before you made those changes

2. this was the most important one for me: make sure the .wav file and the transcription actually match. I didn't realize in my transcription there was some line numbers that were accidentally included. however, in the audio file, the speaker didn't say these line numbers. so you'll need to open up your audio and transcription file and make sure whatever is said in the audio file is matched 100% by the transcription

**Comment by hanspaa2017108** [comment]
> some things that helped me fix this error:
> 
> 1. make sure whenever you rerun the "mfa validate" or "mfa align" commands from the same folder where you have made changes to the TextGrid or .wav files, e.g. "c:/asr_project/speech_corpus", you need to first delete the folder with the same name in the MFA's source location on your computer, for me, it is "C:\Users\user_name\Documents\MFA\speech_corpus". otherwise, I find that "mfa validate" and "mfa align" will still reference the old data in your folder before you made those changes
> 2. this was the most important one for me: make sure the .wav file and the transcription actually match. I didn't realize in my transcription there was some line numbers that were accidentally included. however, in the audio file, the speaker didn't say these line numbers. so you'll need to open up your audio and transcription file and make sure whatever is said in the audio file is matched 100% by the transcription

@halannhile Hey, I had same errors as you mentioned above still no success, tried same with 2 different datasets but still same issue, is it due to MFA latest version or something that I'm missing ?
