### ISSUE TITLE
MFA v2.0

### ISSUE THREAD

**Issue by cveaux** [MontrealCorpusTools/Montreal-Forced-Aligner#193]
Hi,

this is not really an issue but I've seen that there is a new branch MFA v2.0, and I was wondering when you think it would be stable and ready for release? I am particularly interested in some features it seems to have improved like dataset validation with detection of text mismatches. (I tried the current version v1.1 but its dataset validation procedure is not reliable enough on this regard).

Thanks for all the work to keep this project very much advanced,

Christophe

**Comment by machineko** [comment]
@mmcauliffe

**Comment by mmcauliffe** [comment]
Yeah, I've been playing around with some new ideas for supporting MFA going forward.  The main things for 2.0 that I'm primarily targeting are:

* No more frozen executables, rather having installation via pip with some command line scripts installed
* Reducing dependencies on me building some third party software like Phonetisaurus and instead using the conda packages that Kyle Gormon (@kylebgorman) makes available for opengrm-ngram and pynini
* This does however mean that support for Windows native use would be dropped, but I think I'm ok with that since the Bash subsystem for windows works just fine for most things.

Since it's a pretty big change in how things are set up, I'm still doing a fair bit of validation and experimentation, as well as reworking the docs to make sure they're up to date.  The hope is that future fixes would be able to be released faster since there's no freezing process that inevitably has issues.  I'm mostly recovered from my burnout, but I'm still just working on this on the weekends as a side project, so certainly no guarantees on progress.  I think it'd be possible for me to get an alpha version of 2.0 pushed out to pip sometime this month to have people test it now that I've gotten the travis annoyances worked out.

**Comment by cveaux** [comment]
Hi, thanks for the reply. Sorry to hear you went through a burnout, this project has become quite popular and should have been very demanding. I have always installed MFA via `setup.py` and never used the frozen executables indeed. I think it's simple enough to install for most people and surely easier to maintain. Happy to test the new version but no rush there, the current version of MFA is already doing a great job overall.
