### ISSUE TITLE
Document the types of TextGrids that are acceptable.

### ISSUE THREAD

**Issue by nrgslp** [MontrealCorpusTools/Montreal-Forced-Aligner#212]
V2.0 exits with a "no wavs to align" error when the TextGrids supplied for alignment are in TextGrid short form TextGrid. These files have a valid .TextGrid extension and behave as TextGrids in Praat, so the cause of the code failure may not be apparent to users. Consider adding this context to the MFA documentation. More details here: https://github.com/timmahrt/praatIO/issues/23#issue-786445399

**Comment by mmcauliffe** [comment]
It looks like there was a recent update in the textgrid package targetting short textgrids (always forget they're a thing).  I'll take a look at praatIO as well, since it looks like it's more actively developed and tested as a potential better dependency for handling textgrids more recently. Thanks for this!
