### ISSUE TITLE
Inconsistent PronunciationAcousticMismatchError

### ISSUE THREAD

**Issue by nrgslp** [MontrealCorpusTools/Montreal-Forced-Aligner#213]
Hi again. I am running 1.0 on Windows, in a for loop in Command Prompt. The loop iterates through subdirectories of speakers because I had trouble passing it the full corpus of 140k utterances. 
`for /D %s in (.\*) do c:\...\mfa\bin\mfa_align.exe c:\...\job-1\%s\ c:\...\job-1.dict english c:\...\job-1b\  -j 8 -i `

I get this error on only a subset of the directories while setting up the corpus information:
`Traceback (most recent call last):
File "aligner\command_line\align.py", line 186, in <module>
File "aligner\command_line\align.py", line 140, in validate_args
File "aligner\command_line\align.py", line 135, in align_included_model
File "aligner\command_line\align.py", line 88, in align_corpus
File "aligner\models.py", line 129, in validate
aligner.exceptions.PronunciationAcousticMismatchError: There were phones in the dictionary that do not have acoustic models:`

I am passing the same dictionary every time, from a closed set of utterances. Why is the corpus validation unsuccessful in a subset of the iterations (versus, all/none)?

I should mention that I've run the MFA successfully for multiple projects in the past, but I'm having a hell of a time getting things set up during the pilot run for my dissertation. I presume the trouble is due to the corpus size. Any advice on how to handle this would be greatly appreciated because it's a great tool and I'm grateful that it exists.

**Comment by mmcauliffe** [comment]
Sure, yeah, happy to help more, if you could elaborate on your use case a bit.  

* Each of the 140k utterances are single word tokens, correct?  
* What was the issue with the whole corpus? If it ran out of memory, what's the memory on your machine?  The LibriSpeech corpus that's used for source data is about 290k utterances longer than single words, so I feel like it should scale reasonably well to your data.
* This is English data?  
* Just to verify, you are are using 1.0.1 rather than 1.0, correct?
 
Also, if you want to email me the dictionary file (michael.e.mcauliffe@gmail.com), I can take a look through and see if anything's pops out.

Sorry that you've been having so many issues with this!

**Comment by nrgslp** [comment]
Thanks! Please, no apologies - it's a great tool.
Yes 140 single-word tokens of American English organized into speaker-specific folders. 

So, that is a good point. The manifest indicates I am running 1.0.0.0. However, the following list applies to both v2.0 and v1.0, unless specify otherwise.

- Error: There were phones in the dictionary that do not have acoustic models
- Key errors on specific files that exist and I expected to run 
-  Error in train:
 ```
  File ".../montreal_forced_aligner/corpus/align_corpus.py", line 459, in create_subset
    subset_utts = set(random.sample(larger_subset, subset))
  File ".../python3.8/random.py", line 363, in sample
    raise ValueError("Sample larger than population or is negative")
ValueError: Sample larger than population or is negative
```

- Error in validate: 
```
  File ".../montreal_forced_aligner/validator.py", line 273, in analyze_missing_features
    file_name, begin, end = self.corpus.segments[utt].split()
ValueError: too many values to unpack (expected 3)

```
This is in addition to general v2.0 install/file format issues:
- Issue 212 I worked out yesterday - figuring out that a WAV warning was due to TG formatting.
- openblas needed to be installed directly for me
- I was stuck in a scenario in which the MFA was printing "all required kaldi binaries were found!" and then an error message that said (more or less) "check for missing binaries". In this case openfst needed to be added to my path.

And misc issues I was able to work out on my own:
-TGs not appearing in output dir, despite no errors/nothing in log. I solved this by deleting the temp corpus files and incrementing the name of the output dir with each pass. (-c/-t did not help me here.)

I gave up on training and am now just trying to align using the adult models (my data is child speech) until I am set up on the high performance computing cluster. The biggest issue in not running it on the entire corpus was that I would get several hours in and then it would exit due to error, rinse and repeat. I can enter any of these as separate issues - I am new to GitHub and am not totally sure of pragmatics/etiquette. 

I will take you up on your offer to email the .dict because I am hoping to learn as much as I can about the tool - it will be a part of my life for a long while I believe. 

Thanks!

**Comment by mmcauliffe** [comment]
Ok so I looked through the dictionary, it looks like the entries that have troubles are:

```
stren S T R EH N
tr TR
pandabear P AE1 N D AX0 B EY1 R
```

with the phones `EH`, `TR` and 'AX0` causing issues.  I've updated the validation utility for checking this (previously it wasn't actually loading the `acoustic_model_path` param or validating it at all).  The reason you'll run into inconsistencies in having this pop up, for reference, is that one of the optimizations in alignment is to subset the dictionary to remove words that don't appear in transcripts, so chances are some of the subsets you were running didn't include these words while others did.  I've changed the validation utility to not subset (since optimization isn't as relevant there).

I updated the installation instructions in the branch I've been working on to directly include installing openblas from conda-forge, so that should cover those errors.  I'll take a look at the thirdparty binary code to make it look up whether it should indeed be included in the kaldi binaries.

Not sure why the TGs wouldn't appear in the output, but I've done a lot of updating to logging and how cleaning works, so hopefully these changes will address these issues or allow for clearer debugging and logs.  The next update should be out once I finish up some speaker classification functionality that I've been focused on lately.

Thanks for finding all these issues, I do always appreciate the testing!  In general I think separate issues are better than monolith ones for tracking and resolving, but I don't really care too much about it beyond fixing what's broken.

**Comment by nrgslp** [comment]
Thank you for the close look at the dictionary. Your description of the validation optimization (plus changes) makes sense, as well as the other things you mention. I will try rerunning validation with a corrected dictionary to see if I still get that error. If not, I will open a stand-alone issue.
