### ISSUE TITLE
when generate a new dictionary, get error

### ISSUE THREAD

**Issue by zhangsanfeng86** [MontrealCorpusTools/Montreal-Forced-Aligner#238]
Hello,
when generate a new dictionary, get error

![image](https://user-images.githubusercontent.com/73547638/109789238-1ca68a80-7c4b-11eb-8c8e-6c64208da41e.png)

**Comment by mmcauliffe** [comment]
What's the version of Pynini that you're using, that looks like a potentially more recent version than 2.1.0?  The current set up doesn't use the most recent version of Pynini, since the code I was adapting doesn't.  Try running `conda install -c conda-forge openfst=1.7.6 pynini=2.1.0 ngram=1.3.9 baumwelch=0.3.1`, that should ensure that the versions are correct.

**Comment by zhangsanfeng86** [comment]
Thank you,
pynini=2.1.0 is OK.
