### ISSUE TITLE
Beam values in basic_align.yaml  (MFA v2.0)

### ISSUE THREAD

**Issue by cveaux** [MontrealCorpusTools/Montreal-Forced-Aligner#240]
Hi, in the config file for alignment `montreal_forced_aligner/config/basic_align.yaml` the values of `beam` and `retry_beam` are 100 and 400 respectively. However this seems inconsistent with the values used in the __init__ of `AlignConfig` which are 10 and 40. And in `basic_train.yaml` the values of `beam` and `retry_beam` are 10 and 40 too. So I was wondering if there was a typo in `basic_align.yaml` and if not, why this different order of magnitude between training and alignment.

Thanks.

**Comment by mmcauliffe** [comment]
Right so originally, I went with 10 and 40 for both, because that was the values used in Kaldi examples.  It's more important to have a tighter beam for training, because generally if you're more accepting of "worse" alignments, then you could be introducing errors into the acoustic models that overall lead to worse performance.  This is also the reasoning behind the subset logic for monophone, where you take the shorter utterances that are likely to have better alignments to bootstrap quick early versions of training before scaling up. Additionally, tighter beams are computationally faster.

On the pretrained aligner side, there were a number of issues that were raised using MFA outside of the original scope (trying to align longer sound files, production experiment data with long pauses between each token, etc), and so a more relaxed beam is helpful there.  Also any sort of difference in the data is going to cause worse alignment, so it's helpful to relax the beam for that.

**Comment by cveaux** [comment]
I see, interesting about the subset logic for monophone, I didn't quite grasp it or actually thought that is was simply because you need less data to estimate a monophone model but didn't see that the shorter utterances were selected.

Ok, so in my case I'm using the alignment also as a way to clean datasets from text/audio mismatches (or wrong phonetisation) befire using them for other trainings. So I will certainly revert to 10 and 40. Maybe I should use the `--test_transcriptions` of the validation utility as a better way to clean the dataset though.
