### ISSUE TITLE
flac support for segmenting large files?

### ISSUE THREAD

**Issue by tensorfoo** [MontrealCorpusTools/Montreal-Forced-Aligner#250]
hi, i'm aiming to prepare  ~1000hrs of audio data and align it with MFA. I noticed `mfa create_segments <input dir> <output-dir>` didn't pick up the FLAC I put in to test but it handled the WAVs just fine?

My original data is approx 750mb mp3 files, which I normalize with ffmpeg or audacity to 16bit, 16khz mono audio, which results roughly in a 4.5GB FLAC file and a 8GB WAV.

 The FLAC is a lot sharper for having a large dataset, especially if you're going to move it into the cloud for GPU training later down the line (eg colab). It would be nice to be able to use FLAC but I don't know what the downsides would be?

**Comment by mmcauliffe** [comment]
Right, yes at the moment only .wav files are supported.  I'll have to think about flac more generally, I think the bottleneck would be on the Kaldi side, since the python package I've been using does support flac.  It would basically be a matter of requiring sox or ffmpeg to do the conversion/pipe it to kaldi.

As insight into the background, my original intention in only supporting wav is because kaldi does that normally, and relies on scripts/other programs to convert to wavs in their recipes anyway.  In linguistics, wavs are the default, so I don't run into other formats as much, but if flacs are more standard in ASR corpora, I can see supporting them as well.  There's just so many formats out there that I *could* add support for, but they'd all have to be converted to wav in the end anyway.
