### ISSUE TITLE
Arpabet (Stressed) for German, does it exist?

### ISSUE THREAD

**Issue by PedroDKE** [MontrealCorpusTools/Montreal-Forced-Aligner#268]
This is quite an unusual request i think (it is not related to code, but i wasn't sure where else i could ask this), but I'm looking for an acoustic model for German but that uses the Arpabet (Stressed) phoneme set if possible? The way i get it, arpabet has been mainly designed/made for English, but for a project im working on it would interesting if i could phonemise German by using Arpabet (Stressed).
Maybe this makes no sense as English and German are quite different i can imagine. But i'm not from a linguistics field so i'm asking anyway.

Thank you in advance :)

**Comment by mmcauliffe** [comment]
So as you allude to, it would be pretty difficult to map German phones to Arbabet, since it was designed primarily for one specific variety of English (and even then doesn't really capture that variety particularly well for alignment purposes, like having syllabic L, M, N, be represented by "AH0 L").  For mapping German to it, the issues you would run into (off the top of my head):

* in the vowel space with rounded front vowels in German having no equivalent in English
* mapping German "r" (uvular fricative/approximate) to some English sound (English r is alveolar/retroflex approximate)
* mapping German "ch" (palatal/velar fricative) to some English sound (maybe h?)
* German "z" (/ts/ affricate) might also pose some issues mapping to English

I guess the main follow up question would be why having a German Arpabet model would be useful for you?  There might be other solutions that work better.

**Comment by PedroDKE** [comment]
@mmcauliffe thank you for the response :)

I don't know much about phonemes but I already suspected that it might not make much sense to take a phoneme set designed for English and use it for German. 
I was wondering if it would be possible because for a project that i'm working on it would be nice to have both my English and German sentences in the same phoneme set. But as the [pretrained acoustic models](https://montreal-forced-aligner.readthedocs.io/en/stable/pretrained_models.html#pretrained-acoustic-models) for the MFA between German and English support different sets i will try by using both phonemesets.
Do you know if there's a particular reason why theres no Prosodylab/Globalphone model for English? Would it not make sense because arpabet is much better suited for English or is there a lack of training data?
