### ISSUE TITLE
why does the aligner work for these cases ?

### ISSUE THREAD

**Issue by swarajdalmia** [MontrealCorpusTools/Montreal-Forced-Aligner#283]
The text for the transcript and the audio transcript can be found below :

I used both mfa validate and mfa align but they don't give any errors. Why is this happening ?

example 1 : change in word sequence
- text : this is a big fluffy dog
- audio transcript : this is a fluffy big dog.

example 2 : a subword present in text that is not present in audio
- text : these pineapples are green
- audio transcript : these apples are green

example 3 : a subword is present in the audio but not the text
- text : these apples are green
- audio : these pineapples are green

Additionally would the other aligners out there be able to detect these errors ?

**Comment by mmcauliffe** [comment]
So forced alignment takes the transcript as ground truth and then needs to be robust enough to deal with variations in speaking rate, microphone quality, dialect, gender, idiosyncrasies, etc.  Additionally the default beam for aligning with a pretrained model is fairly wide, you can try to reduce it to the training levels by adding the flag `--beam 10` to `mfa align...` that may cause alignment to fail on the cases where the transcription deviates from the audio too much.

There is a `--test_transcriptions` flag for `mfa validate` which similar to a biased LM approach (some background here: https://arxiv.org/pdf/1904.04294.pdf).  The algorithm in test_transcriptions makes a unigram LM from the transcript plus the top X most frequent words and then tries to transcribe the utterance and notes differences.  In my experience though, it's not great usually, due to the aforementioned other sources of variability, so there's lots of false positives and noise to sort through, but it might be a decent starting point for you.

You might be able to get better mileage by running the transcripts through a more sophisticated ASR system (https://coqui.ai/) and then using that to diagnose the errors.
