### ISSUE TITLE
About the result of alignment

### ISSUE THREAD

**Issue by azraelkuan** [MontrealCorpusTools/Montreal-Forced-Aligner#312]
why there is no 'sp' or 'sil' in the mfa2.0 result? and the text is "".
![image](https://user-images.githubusercontent.com/23380152/126159617-7fdd4bd5-edc4-4cd4-845b-4dcc293dadda.png)

**Comment by mmcauliffe** [comment]
In the latest release I changed the behavior to remove all "sil" or "sp" outputs since they usually just result in a very cluttered textgrid, especially when aligning longer sound files with segments.  I don't think there's much information lost here, but let me know if you have a need for explicitly have silence in the textgrids.

**Comment by azraelkuan** [comment]
@mmcauliffe thanks for quick reply, it is ok for this style.

**Comment by yiwei0730** [comment]
@mmcauliffe If i want to add the information 'sp' and 'sil', how do i change the code?
