### ISSUE TITLE
Showing a mismatch of dictionary and model phones 

### ISSUE THREAD

**Issue by Jueun0505** [MontrealCorpusTools/Montreal-Forced-Aligner#317]
Hi, 

Firstly, I would like to appreciate your great work! I am recently studying MFA for my research paper as a Linguist. I find it very hard to learn alone but I do admire the usefulness of the program. 

Background Information for the problem
-4 Korean speakers 
-100 sentences as wav. forms for each speaker
-Dictionary for the phoneme of the current data is extracted by using codes as follows: mfa train_g2p korean_dict.txt korean.zip

My problem that I encounter is that the Korean phoneme dictionary does match with a pretrained acoustic model provided by mfa. The terminal says as follows with no error message so that I have no clue/orientation what to fix:

(aligner) june@Juneui-MacBookAir test_my_work % mfa align audio korean_dict.txt model/korean.zip out
All required kaldi binaries were found!
/Users/june/Documents/MFA/audio/align.log
WARNING - WARNING: Using old temp directory, this might not be ideal for you, use the --clean flag to ensure no weird behavior for previous versions of the temporary directory.
INFO - Setting up corpus information...
INFO - Number of speakers in corpus: 4, average number of utterances per speaker: 100.0
INFO - Parsing dictionary without pronunciation probabilities without silence probabilities
dictionary phones: {'ᆱ', 'ᄃ', 'ᄌ', 'ᅦ', 'ᄒ', 'ᄍ', 'ᆲ', 'ᇀ', 'ᅵ', 'ᄂ', 'ᄎ', 'ᆸ', 'ᅪ', 'ᄑ', 'ᄐ', 'ᅱ', 'ᄈ', 'ᆮ', 'ᆶ', 'ᅧ', 'ᄀ', 'ᄊ', 'ᅲ', 'ᆻ', 'ᅢ', 'ᆽ', 'ᄆ', 'ᆹ', 'ᅨ', 'ᄁ', 'ᄅ', 'ᆰ', 'ᅯ', 'ᄋ', 'ᅴ', 'ᅮ', 'ᆺ', 'ᆫ', 'ᆭ', 'ᆩ', 'ᄄ', 'ᅩ', 'ᇂ', 'ᇁ', 'ᄏ', 'ᅡ', 'ᆾ', 'ᅫ', 'ᅭ', 'ᅣ', 'ᅬ', 'ᆼ', 'ᆷ', 'ᅳ', 'ᆨ', 'ᄇ', 'ᆯ', 'ᄉ', 'ᅤ', 'ᅥ'}
model phones: {'D', 'k', 'AE', 'DD', 'N', 'S', 'UE', 'oA', 't', 'O', 'iO', 'NG', 'G', 'euI', 'L', 'JJ', 'B', 'GG', 'Ph', 'iA', 'iE', 'R', 'SS', 'U', 'M', 'H', 'I', 'uEO', 'OE', 'EO', 'Th', 'E', 'J', 'A', 'iU', 'EU', 'Kh', 'BB', 'p', 'CHh', 'iEO'}
There were phones in the dictionary that do not have acoustic models: ᄀ, ᄁ, ᄂ, ᄃ, ᄄ, ᄅ, ᄆ, ᄇ, ᄈ, ᄉ, ᄊ, ᄋ, ᄌ, ᄍ, ᄎ, ᄏ, ᄐ, ᄑ, ᄒ, ᅡ, ᅢ, ᅣ, ᅤ, ᅥ, ᅦ, ᅧ, ᅨ, ᅩ, ᅪ, ᅫ, ᅬ, ᅭ, ᅮ, ᅯ, ᅱ, ᅲ, ᅳ, ᅴ, ᅵ, ᆨ, ᆩ, ᆫ, ᆭ, ᆮ, ᆯ, ᆰ, ᆱ, ᆲ, ᆶ, ᆷ, ᆸ, ᆹ, ᆺ, ᆻ, ᆼ, ᆽ, ᆾ, ᇀ, ᇁ, ᇂ

I presume that I might have to match the Korean phonemes with English one in the dictionary file (picture attached)
![dictionary](https://user-images.githubusercontent.com/88170875/127593783-a1e53d88-4c3b-4e4d-9805-868e5266b3aa.png)

I would be very grateful if you could provide some help! 

Many thanks!

**Comment by mmcauliffe** [comment]
Looks like you're training your own G2P model (which is then outputting jamo as phones), whereas the prebuilt Korean model uses GlobalPhone phone set.  You can get the appropriate G2P model via `mfa download g2p korean_hangul_g2p` or `mfa download g2p korean_jamo_g2p`, I believe.  The jamo version is generally more accurate, since there's a smaller grapheme set.  You can see the accuracies here: https://montreal-forced-aligner.readthedocs.io/en/latest/pretrained_models.html#pretrained-g2p-models

Once you have the model downloaded, you should be able to generate the appropriate dictionary via the `mfa g2p korean_jamo_g2p audio korean_dict.txt` (going off of your align commands).  And then once that completes, you can use the `korean_dict.txt` file in the align command and the phonesets should be correct.  See more details here: https://montreal-forced-aligner.readthedocs.io/en/latest/g2p_dictionary_generating.html

Hope that helps!

**Comment by Jueun0505** [comment]
Wow, it does work!!! Thank you so much for your instant feedback and above all for the helpful advice!! Thank  a lot!!!
