### ISSUE TITLE
How to train alignment (version 2.0) using past config(version 1.0)

### ISSUE THREAD

**Issue by gmltmd789** [MontrealCorpusTools/Montreal-Forced-Aligner#332]
Hi,

First of all, thank you for providing such a good tool. 
I have a question while experimenting with the tool.

When I train my dataset to version 1.0.1, there is no unaligned sample.
However, when training with the latest version (2.0.0 or higher), unaligned samples occur.
When I checked, it seems that there was a difference in the results because LDA or other methods of additional align were inserted in version 1.1 or later.
I can get alignment by using 1.0, but training is very slow due to multiprocessing issues in lower versions, so I want to use 2.0 or higher.
**So I'm wondering what config I need to provide in v2.0+ to get the same result as v1.0.1**

When using the default config of version 1.0 as shown below for version 2.0, an error of No field found for key fmllr_power occurred.
![image](https://user-images.githubusercontent.com/49265950/133364505-05ec57f3-d7c5-41ce-8a57-79d69cd62ba9.png)
[LINK FOR CONFIG
](https://montreal-forced-aligner.readthedocs.io/en/latest/configuration_align.html#training-configuration-for-1-0)If fmllr_power is removed, training is performed, but the result is different from 1.0.1. (Unaligned samples exist.)

**Comment by mmcauliffe** [comment]
Oh sorry about that! The key got renamed at some point to just "power", since it's not a fmllr-specific parameter.  The reason it was `fmllr_power` was to differentiate the power used in SAT versus previous training blocks, since MFA 1.0 wasn't great about separating out namespaces.  I'll update the docs to change "fmllr_power" to just "power", but it should work once you update the key.
