### ISSUE TITLE
Instruction for compiling from source

### ISSUE THREAD

**Issue by tshmak** [MontrealCorpusTools/Montreal-Forced-Aligner#358]
Is there any instruction in the new documentation for compiling from source? 

Also is it possible to read the docs for past versions?

**Comment by mmcauliffe** [comment]
Compiling MFA from source? Or all of the dependencies that are now on conda?  I can add a page for that.

Which version are you looking for?  The 1.0.1 docs are up here: https://montreal-forced-aligner.readthedocs.io/en/stable/, and I can build other earlier versions, what are you looking for there exactly?

**Comment by tshmak** [comment]
I'm just wondering if it's easy/possible to have documentations for all past versions like [pytorch](https://pytorch.org/docs/versions.html), cos we may not always be using the latest versions. 

v1.0.1 seems a long time ago. Do the instructions still apply?

**Comment by tshmak** [comment]
Also I remember being able to specify options for increasing the sample size used in the various steps in `mfa train`. I can't find the documentation for this now. 

I can only find [this](https://montreal-forced-aligner.readthedocs.io/en/latest/user_guide/configuration/index.html), but I seem to remember I used to be able to provide a `.yaml` file for the options used in the different steps...

**Comment by mmcauliffe** [comment]
Yes it's here now:
https://montreal-forced-aligner.readthedocs.io/en/latest/user_guide/configuration/align.html#default-training-config-file.
Currently working on revamping how configuration works internally, but the
config files will be the same, so once the refactor's done, I'll do a pass
of this section of the docs and update it to be more easily navigable.

**Comment by Hocine958** [comment]
Hi, first of all great work, I was wondering as well about the possibility of compiling mfa 2.0 into a standalone executable for windows ? I don't know if it's still possible to "freeze" this version since the shift to conda packaging ? If so I would be interested in the how to.
Thank you.

**Comment by mmcauliffe** [comment]
I've added back the section on installing from source: https://montreal-forced-aligner.readthedocs.io/en/latest/installation.html#installing-from-source, as well as revamped the the configuration section in light of the recent refactor: https://montreal-forced-aligner.readthedocs.io/en/latest/user_guide/configuration/index.html#configuring-specific-commands.  So I'm going to close this.

In terms of freezing MFA, you can take a look at how it was done in version 1.X: https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/tree/v1.0/freezing, but it was 2 years ago and modern versions of PyInstaller might be better?  Freezing was honestly such an annoying part of the process, likely because I was trying to get it working on three platforms, but if you're just doing it for one, it might be easier, and if you can use the Kaldi binaries from conda for freezing, that'll eliminate one of the bigger hurdles as well.  As the root of it, you'd still just need to pass it the mfa entry point, and as long as all the Kaldi/OpenFst/etc binaries are available on the target system, either frozen or installed separately and on the path, it shouldn't be too bad to freeze just the MFA package.

**Comment by tshmak** [comment]
The default training config file (https://montreal-forced-aligner.readthedocs.io/en/latest/user_guide/configuration/align.html#default-training-config-file) is now 404. 

I'm looking to modify the default setting to use the entire data for all stages of training. 

Anyway, thanks for all your hard work!

**Comment by mmcauliffe** [comment]
Yes, it changed location within the configuration section to under "acoustic modeling" rather than alignment, it's available here: https://montreal-forced-aligner.readthedocs.io/en/latest/user_guide/configuration/acoustic_modeling.html#default-training-config-file

**Comment by tshmak** [comment]
Are the past documentation currently removed?
