### ISSUE TITLE
It take so long to align after validating, the program is still running?

### ISSUE THREAD

**Issue by YoungKang1222** [MontrealCorpusTools/Montreal-Forced-Aligner#368]
Excuse, after validating the corpus and the result is good.
![image](https://user-images.githubusercontent.com/30460985/145173786-b2b3eac0-87a8-4404-a65f-013b4c135f4b.png)

Then I start aligning the corpus and get the textgrid, but **it take long time. I doubt he program is still running.** Could someone help me figuring what is going on? I already get part of textgrid.
![image](https://user-images.githubusercontent.com/30460985/145174289-47629171-f191-46f6-b0ce-157d2fd67e81.png)
![image](https://user-images.githubusercontent.com/30460985/145174356-34ce3308-dfce-4508-9d32-de4ba7ad27b3.png)

**Comment by YoungKang1222** [comment]
how to get updated 2.0.0b9?
I upgrade from 2.0.0b8 as this instruction (https://montreal-forced-aligner.readthedocs.io/en/latest/installation.html#upgrading-from-non-conda-version)but it fails.
![image](https://user-images.githubusercontent.com/30460985/145353192-88b43fa6-b016-418e-9420-a29d078f3a0c.png)
![image](https://user-images.githubusercontent.com/30460985/145353276-8808b684-e47b-4054-b5c5-e8ff6cc70ebe.png)
![image](https://user-images.githubusercontent.com/30460985/145353310-d3a141c7-82de-49dd-ac63-715fb9289980.png)

**Comment by mmcauliffe** [comment]
Ah, those instructions are only if you had previously installed MFA via pip before it was available on conda forge.  The issue that you're running into here is that your conda distribution thinks mfa is still installed because pip was the one that removed it.  You should be able to run `conda update montreal-forced-aligner` and it should pick up the newer version (2.0.0b9 might not be available on conda yet, I just kicked it off 20 minutes ago). 

Alternatively, you can also always just overwrite that environment by calling `conda create -n aligner montreal-forced-aligner` and that should fix it too.

**Comment by YoungKang1222** [comment]
got it. I try the `conda update montreal-forced-aligner`  and as you say b9 is not avaliable:
![image](https://user-images.githubusercontent.com/30460985/145356138-5cc61a73-29be-4f2e-ba47-e61a79915c4a.png)

Then I overwrite but get channel problem
![image](https://user-images.githubusercontent.com/30460985/145356348-a90f5594-d940-4009-9e64-46a3036b52d5.png)
