### ISSUE TITLE
[BUG] Can't align audio using downloaded MFA's ipa model files

### ISSUE THREAD

**Issue by veltzerdoron** [MontrealCorpusTools/Montreal-Forced-Aligner#396]
**Description**
I run mfa align using the download english IPA models and get a report of missing phonemes in the model (I think these are aspirated stops)

**Reproducing my issue**

- install the latest MFA
- download the english_ipa acoustic model and the english_us_ipa dictionary
- align English audio using the followng command:
`mfa align --clean MFATutorial2021/input english_us_ipa english_ipa MFATutorial2021/outpu
`

I believe any Corpus would do.

Also... you wouldn't happen to have code that performs an accuracy test on MFA lying around, would you?

**Comment by mmcauliffe** [comment]
Ah sorry, was hoping to get these fixed up faster, but I've ended up down the rabbit of hole of fixing some larger issues with training to get some better accuracy overall. But yes at the moment, the latest versions won't work with the ipa model, since it depends on some `multilingual_ipa` code that was removed in [2.0.0b11](https://montreal-forced-aligner.readthedocs.io/en/latest/changelog/changelog_2.0.html#b11), so if you try running it on 2.0.0b10, it'll work, but I *should* be in the last phase of getting the models trained and working.

**Comment by mmcauliffe** [comment]
2.0.0rc4 is out along with the updated IPA-based models: https://mfa-models.readthedocs.io/en/latest/

**Comment by veltzerdoron** [comment]
So, for instance, if I wish to align American English IPA I should use the english_us_ipa dictionary and english_mfa acoustic model?

**Comment by mmcauliffe** [comment]
Yes, the english_us_mfa dictionary: https://mfa-models.readthedocs.io/en/latest/dictionary/English/English%20%28US%29%20MFA%20dictionary%20v2_0_0.html#English%20(US)%20MFA%20dictionary%20v2_0_0.  Any dictionaries named "ipa" are deprecated and probably don't work, since they've undergone a significant revision from the initial work I did on them.

**Comment by veltzerdoron** [comment]
Wouldn't want to bud into the holy work you're undertaking but personally, I would vote for removing models that are non functional, it makes for bad press if someone were to use them first before trying the updated ones.
