### ISSUE TITLE
Export to TextGrid step taking too long due to db access pattern[BUG]

### ISSUE THREAD

**Issue by kdonbekci** [MontrealCorpusTools/Montreal-Forced-Aligner#437]
[x] Have you updated to latest MFA version?
Running 2.0.0rc5.
[x] Have you tried rerunning the command with the `--clean` flag?
Yes
**Describe the issue**
This is similar to the discussion #249 but with more detail regarding the cause of the slowdown. I have added my comments in the discussion on that issue. Creating this new issue as #249 is not assigned to anyone. 

Basically, the Export to TextGrid part of the alignment takes forever long on MFA 2.x. Running on TIMIT for instance, this step takes 17 minutes. There is something going on with the DB access pattern inside the `alignment/multiprocessing.py`'s `construct_output_tiers` function, with the `subqueryload` statements which cause `fetchall` kicks to happen for each utterance. I've added a hack to overcome this at the end of the discussion on #249 where I basically avoid the `subqueryload` statements, and perform two additional queries inside the for loop to the `PhoneInterval` and `WordInterval` tables using the `utterance_id` key which I indicate as an index in the `corpus/db.py` definitions. 

Love the new dictionaries and acoustic models, but this bug limits the applicability of the new version to large datasets.

**Comment by mmcauliffe** [comment]
Thanks for this and the investigation, very much appreciated! I'll do some benchmarking and play around with some other options for the preloading, that should be faster that running two additional queries for each utterance, so my guess is the fastest would be adding the missing indices for the foreign keys, using `selectinload` instead of `subqueryload` and relying on the eager loading, since that would be just 2 queries rather than 1 +2*(num_utterances).

**Comment by dunky11** [comment]
I can confirm this:

![image](https://user-images.githubusercontent.com/35628149/165369608-d2e5f9bb-bfa6-4a02-b298-7961f8a33c36.png)

Everything until the step took ~6 minutes, the step took 2 hours for 17k files.
