### ISSUE TITLE
Detect and report on malformed pronunciation dictionary lines

### ISSUE THREAD

**Issue by TaylorWJones** [MontrealCorpusTools/Montreal-Forced-Aligner#45]
background: I have used MFA to successfully train two aligners on the same corpus, one using eng.dict, and one using a novel dictionary I wrote by applying appropriate phonological rules to eng.dict

I attempted to train a third model, invoking:

`bin/mfa_train_and_align ./CORAAL/CORAAL_DC1 ./AAL1.dict ./CORAAL_Aligned3 -o coraal3.zip -f -v`

it tells me it's setting up the corpus information, creates the output directory, then crashes with the error:

`Traceback (most recent call last):
  File "/Users/mmcauliffe/dev/Montreal-Forced-Aligner/aligner/command_line/train_and_align.py", line 165, in <module>`

  `File "/Users/mmcauliffe/dev/Montreal-Forced-Aligner/aligner/command_line/train_and_align.py", line 53, in align_corpus`

  `File "/Users/mmcauliffe/dev/Montreal-Forced-Aligner/aligner/dictionary.py", line 115, in  #__init__
IndexError: list index out of range`

`Failed to execute script train_and_align`

I have attempted to rewrite the dictionary multiple times, but cannot seem to fix the error. The aligner still works with the other novel dictionary...I'm not sure what the problem could be.

**Comment by mmcauliffe** [comment]
It looks like it's caused by there not being a pronunciation following the orthography for one of the words, so somewhere there's a line that looks like:

```
worda
wordb phonea phoneb
```

The error message is indeed opaque, so I'll add some checking to it and better reporting (i.e., what line number is lacking a pronunciation) for the next release.  In the meantime, your best bet might be to write a simple python script to look for lines without spaces in the file.

**Comment by TaylorWJones** [comment]
This solved it. Thank you!
