### ISSUE TITLE
mandarin_mfa_dict words with pinyin "mo", their phonemes not correct ! ? [bug]

### ISSUE THREAD

**Issue by EzerbelCN** [MontrealCorpusTools/Montreal-Forced-Aligner#465]
**Describe the issue**

In my opinion , in my mother tongue of mandarin ,

"魔" "磨" and other words with pinyin : "mo" , 

their phonemes should be " m o " , not "m w o" .

![image](https://user-images.githubusercontent.com/66873183/173343937-675414a2-fd80-4da5-aa74-81a7eaa6486e.png)

by the way, what`s the meaning of the numbers before phonemes?

time span or some other advanced atrribute?

Im making a lip sync project , this problem really confused me.

thanks!

**Comment by mmcauliffe** [comment]
It looks like that's from wiktionary, if you click "more" here: https://en.wiktionary.org/wiki/%E9%AD%94#Pronunciation, you'll see it's listed as /mwɔ³⁵/.  That might just be a transcription idiosyncrasy in wiktionary.  Do you think the "w o" sequence in general should be represented just as "o"?  I don't know much about Mandarin dialects and phonology, so happy to incorporate any changes that will make the dictionary better!  

For the numbers, see https://montreal-forced-aligner.readthedocs.io/en/latest/user_guide/dictionary.html#silence-probabilities, I'm working on expanding out some docs related to this since it's newer functionality, but the first number is the probability of the pronunciations given the orthography, the second number is the probably of silence following this pronunciations, and the final two numbers represent corrections on the likelihood of silence or speech before the pronunciation.  This helps capture pronunciation variants that are dependent on surrounding silence.  For instance, in the word "lot", the final t can be realized as a full [t], a flapped [ɾ], or a glottal [ʔ] in American English dialects.  The flapped variant is only going to be found in connected speech like "a lot of things" and never before silence like in "our car is in the parking lot".
