### ISSUE TITLE
[BUG] mfa align fails with italian_cv model which uses epitran phoneset. 

### ISSUE THREAD

**Issue by macsharma** [MontrealCorpusTools/Montreal-Forced-Aligner#484]
**Debugging checklist**

[ ] Have you updated to latest MFA version? Yes
[ ] Have you tried rerunning the command with the `--clean` flag? Yes

**Describe the issue**
mfa align using italian_cv model which uses epitran phoneset results in the error. 

Steps followed:
1) Downloaded the italian acoustic model : https://mfa-models.readthedocs.io/en/latest/acoustic/Italian/Italian%20CV%20acoustic%20model%20v2_0_0.html#Italian%20CV%20acoustic%20model%20v2_0_0

2) Downloaded the italian dictionary: https://mfa-models.readthedocs.io/en/latest/dictionary/Italian/Italian%20CV%20dictionary%20v2_0_0.html

3) Trained a g2p model using the dictionary:  mfa train_g2p %s %s -v'%(source_dict_path, g2p_model_path)

4) Used the trained g2p model to get dictionary on the corpus: mfa g2p italian_cv <corpus_path> <dictionary_path> --clean --overwrite -j 3 -q

5) Used  the mfa align: mfa align <corpus_path> <dictionary_path> italian_cv <output_path> --clean --overwrite --output_format json -j 8 -q

The issue seems to be of phoneset. Can you help on how to use italian_cv model with epitran phoneset.

**For Reproducing your issue**
Please fill out the following:

1. Corpus structure
   * What language is the corpus in? Italian
   * How many files/speakers? ~18 
   * Are you using lab files or TextGrid files for input? txt
2. Dictionary
   * Are you using a dictionary from MFA? If so, which one? italian_cv
   * If it's a custom dictionary, what is the phoneset?
3. Acoustic model
   * If you're using an acoustic model, is it one download through MFA? If so, which one? italian_cv
   * If it's a model you've trained, what data was it trained on?

**Log file**
Please attach the log file for the run that encountered an error (by default these will be stored in `~/Documents/MFA`).

Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/aligner/bin/mfa", line 11, in <module>
    sys.exit(main())
  File "/home/ubuntu/anaconda3/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/command_line/mfa.py", line 1067, in main
    run_align_corpus(args, unknown)
  File "/home/ubuntu/anaconda3/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/command_line/align.py", line 106, in run_align_corpus
    align_corpus(args, unknown_args)
  File "/home/ubuntu/anaconda3/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/command_line/align.py", line 31, in align_corpus
    aligner = PretrainedAligner(
  File "/home/ubuntu/anaconda3/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/alignment/pretrained.py", line 65, in __init__
    super().__init__(**kw)
  File "/home/ubuntu/anaconda3/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/alignment/base.py", line 68, in __init__
    super().__init__(**kwargs)
  File "/home/ubuntu/anaconda3/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/corpus/acoustic_corpus.py", line 1020, in __init__
    super().__init__(**kwargs)
  File "/home/ubuntu/anaconda3/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/corpus/acoustic_corpus.py", line 93, in __init__
    super().__init__(**kwargs)
  File "/home/ubuntu/anaconda3/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/corpus/base.py", line 98, in __init__
    super().__init__(**kwargs)
  File "/home/ubuntu/anaconda3/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/abc.py", line 464, in __init__
    super().__init__(**kwargs)
  File "/home/ubuntu/anaconda3/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/abc.py", line 286, in __init__
    super().__init__(**kwargs)
  File "/home/ubuntu/anaconda3/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/dictionary/multispeaker.py", line 147, in __init__
    super().__init__(**kwargs)
  File "/home/ubuntu/anaconda3/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/dictionary/mixins.py", line 927, in __init__
    super().__init__(**kwargs)
  File "/home/ubuntu/anaconda3/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/alignment/mixins.py", line 82, in __init__
    super().__init__(**kwargs)
  File "/home/ubuntu/anaconda3/envs/aligner/lib/python3.8/site-packages/montreal_forced_aligner/dictionary/mixins.py", line 467, in __init__
    phone_set_type = PhoneSetType[phone_set_type]
  File "/home/ubuntu/anaconda3/envs/aligner/lib/python3.8/enum.py", line 387, in __getitem__
    return cls._member_map_[name]
KeyError: None

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, OSX, Linux] linux
 - Version [e.g. MacOSX 10.15, Ubuntu 20.04, Windows 10, etc] ubuntu 18.04
 - Any other details about the setup (Cloud, Docker, etc): EC2

**Additional context**

**Comment by ysviru** [comment]
I received the same error when trying the italian_cv model. 
I know the source of this error, but I don't know how to fix it. 

The data I use is under a folder called _it_corpus_ and contains a single .mp3 audio file and corresponding text inside a single .lab file. 

_**Attempt 1**_

For all acoustic models that use the epitran phoneset (italian_cv, polish_cv, portuguese_cv, etc.), I see that the meta.yaml file (contained inside the acoustic model zip file) uses phone_set_type as "null". This causes the above mentioned KeyError since "null" (or I guess None) is not a valid type for the enum PhoneSetType.  

To solve this, I changed the meta.yaml to have the phone_set_type as "IPA" (since epitran uses IPA), but this does not work either.  I obtain the following error -- 

------------------------------------------------------------------------------------------------------------------

mfa align --verbose --beam=500 --retry_beam=4000 --overwrite --clean --output_format json ~/Desktop/it_corpus  italian_cv italian_cv ~/Desktop/it_corpus/mfa_output


DEBUG - Beginning run for pretrained_aligner on it_corpus
DEBUG - Using multiprocessing with 3
DEBUG - Set up logger for MFA version: 2.0.0rc9
DEBUG - Cleaned previous run
WARNING - Skipped the following configuration keys: pitch
DEBUG - There were some differences in the current run compared to the last one. This may cause issues, run with
                 --clean, if you hit an error.
DEBUG - Using IPA
DEBUG - Loaded dictionary in 2.195952892303467
DEBUG - Wrote lexicon information in 2.8991498947143555
INFO - Setting up corpus information...
DEBUG - Could not load from temp
INFO - Loading corpus from source files...
  0%|                                                                                                                                                        | 0/100 [00:00<?, ?it/s]DEBUG - Processing queue: 0.11268099999999937
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.02s/it]
DEBUG - Parsed corpus directory with 3 jobs in 0.12958900000000018 seconds
INFO - Found 1 speaker across 1 file, average number of utterances per speaker: 1.0
DEBUG - Loaded corpus in 6.347387790679932
INFO - Initializing multiprocessing jobs...
WARNING - Number of jobs was specified as 3, but due to only having 1 speakers, MFA will only use 1 jobs.
DEBUG - Initialized jobs in 0.007718086242675781
INFO - Creating corpus split for feature generation...
DEBUG - Created corpus split directory in 0.0069010257720947266
INFO - Generating base features (mfcc)...
INFO - Generating MFCCs...
  0%|                                                                                                                                                          | 0/1 [00:02<?, ?it/s]
INFO - Calculating CMVN...
INFO - Creating corpus split with features...
DEBUG - Generated features in 2.0648529529571533
DEBUG - Calculated oovs found in 0.00788569450378418
DEBUG - Setting up corpus took 13.53178882598877 seconds
ERROR - There was an error in the run, please see the log.
PronunciationAcousticMismatchError:

  There were phones in the dictionary that do not have acoustic models: 
  dʒ, h, ts, and tʃ

------------------------------------------------------------------------------------------------------------------

_**Attempt 2**_

I think the above error happens since the acoustic model does not support these phones that montreal thinks a model with phone_set_type as IPA should support.  

So I tried to add these unsupported phones to the acoustic model's meta.yaml file under the phones section. (I know that this is a hack, but my thinking was that since the italian_cv dictionary would never produce these 4 unsupported phones, I would never generate them and cause an issue for the acoustic model). This bypasses the PronunciationAcousticMismatchError noted above, but I get another error as shown below -- 

------------------------------------------------------------------------------------------------------------------

(Run after adding unsupported phones to meta.yaml)

mfa align --verbose --beam=500 --retry_beam=4000 --overwrite --clean --output_format json ~/Desktop/it_corpus  italian_cv italian_cv ~/Desktop/it_corpus/mfa_output

DEBUG - Beginning run for pretrained_aligner on it_corpus
DEBUG - Using multiprocessing with 3
DEBUG - Set up logger for MFA version: 2.0.0rc9
DEBUG - Cleaned previous run
WARNING - Skipped the following configuration keys: pitch
DEBUG - There were some differences in the current run compared to the last one. This may cause issues, run with
                 --clean, if you hit an error.
DEBUG - Using IPA
DEBUG - Loaded dictionary in 2.3720102310180664
DEBUG - Wrote lexicon information in 3.0459001064300537
INFO - Setting up corpus information...
DEBUG - Could not load from temp
INFO - Loading corpus from source files...
  0%|                                                                                                                                                        | 0/100 [00:00<?, ?it/s]DEBUG - Processing queue: 0.11803000000000008
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.02s/it]
DEBUG - Parsed corpus directory with 3 jobs in 0.1345970000000003 seconds
INFO - Found 1 speaker across 1 file, average number of utterances per speaker: 1.0
DEBUG - Loaded corpus in 6.295288801193237
INFO - Initializing multiprocessing jobs...
WARNING - Number of jobs was specified as 3, but due to only having 1 speakers, MFA will only use 1 jobs.
DEBUG - Initialized jobs in 0.00899505615234375
INFO - Creating corpus split for feature generation...
DEBUG - Created corpus split directory in 0.0058557987213134766
INFO - Generating base features (mfcc)...
INFO - Generating MFCCs...
  0%|                                                                                                                                                          | 0/1 [00:02<?, ?it/s]
INFO - Calculating CMVN...
INFO - Creating corpus split with features...
DEBUG - Generated features in 2.0766701698303223
DEBUG - Calculated oovs found in 0.007263898849487305
DEBUG - Setting up corpus took 13.814115047454834 seconds

DEBUG - ====ACOUSTIC MODEL INFO====
DEBUG - Acoustic model root directory: /Users/yvvirkar/Documents/MFA/extracted_models/acoustic
DEBUG - Acoustic model dirname: /Users/yvvirkar/Documents/MFA/extracted_models/acoustic/italian_cv
DEBUG - Acoustic model meta path: /Users/yvvirkar/Documents/MFA/extracted_models/acoustic/italian_cv/meta.yaml
DEBUG - Acoustic model meta information:
DEBUG - architecture: gmm-hmm base_phone_regex: null features:   allow_downsample: true   allow_upsample: true
                 feature_type: mfcc   frame_shift: 10   high_frequency: 7800   low_frequency: 20   pitch: false
                 sample_frequency: 16000   snip_edges: true   use_energy: false   uses_cmvn: true   uses_deltas: false
                 uses_speaker_adaptation: false   uses_splices: true   uses_voiced: false multilingual_ipa: false
                 oov_phone: spn optional_silence_phone: sil other_noise_phone: sp phone_set_type: IPA phone_type:
                 triphone phones: !!set   _: null   a: null   "a\u02D0": null   b: null   "b\u02D0": null   d: null
                 "d\u0292": null   "d\u02D0": null   "d\u0361\u0292": null   "d\u0361\u0292\u02D0": null   e: null
                 "e\u02D0": null   f: null   "f\u02D0": null   g: null   h: null   "h\u02D0": null   i: null   j: null
                 k: null   "k\u02D0": null   l: null   "l\u02D0": null   m: null   "m\u02D0": null   n: null
                 "n\u02D0": null   o: null   "o\u02D0": null   p: null   "p\u02D0": null   r: null   "r\u02D0": null
                 s: null   "s\u02D0": null   t: null   ts: null   "t\u0283": null   "t\u02D0": null   "t\u0361s": null
                 "t\u0361\u0283": null   "t\u0361\u0283\u02D0": null   u: null   v: null   "v\u02D0": null   w: null
                 x: null   y: null   z: null   "\xB5": null   "\xBA": null   "\xDF": null   "\xE1": null   "\xE3": null
                 "\xE5": null   "\xE6": null   "\xEB": null   "\xEF": null   "\xF0": null   "\xF1": null   "\xF6": null
                 "\xF8": null   "\xFC": null   "\xFE": null   "\xFF": null   "\u0105": null   "\u0111": null   "\u0117":
                 null   "\u0119": null   "\u011B": null   "\u0127": null   "\u012B": null   "\u0131": null   "\u013E":
                 null   "\u0142": null   "\u0144": null   "\u0148": null   "\u014D": null   "\u0151": null   "\u0153":
                 null   "\u0159": null   "\u015B": null   "\u015F": null   "\u0161": null   "\u016B": null   "\u016D":
                 null   "\u01E9": null   "\u0219": null   "\u021B": null   "\u0254": null   "\u0259": null   "\u025B":
                 null   "\u0261": null   "\u0261\u02D0": null   "\u0272": null   "\u0283": null   "\u028E": null
                 "\u02B9": null   "\u02BB": null   "\u02BC": null   "\u02BE": null   "\u02BF": null   "\u0430": null
                 "\u0431": null   "\u0434": null   "\u0435": null   "\u043B": null   "\u043D": null   "\u043E": null
                 "\u0441": null   "\u0443": null   "\u0446": null   "\u044A": null   "\u0451": null   "\u0459": null
                 "\u04A3": null   "\u05D3": null   "\u05D4": null   "\u05D5": null   "\u0629": null   "\u0631": null
                 "\u0633": null   "\u0635": null   "\u063A": null   "\u0644": null   "\u064A": null   "\u1E31": null
                 "\u1E5B": null   "\u1E61": null   "\u1E63": null   "\u1E6D": null   "\u1EA1": null   "\u1EBD": null
                 "\u1EE5": null   "\u5BB6": null   "\uA78C": null train_date: '2021-12-29 05:42:40.560949' version:
                 2.0.0b9

DEBUG - Setup for alignment in 13.914282083511353 seconds
INFO - Compiling training graphs...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.81s/it]
DEBUG - Compiling training graphs took 2.810559034347534
INFO - Performing first-pass alignment...
INFO - Generating alignments...
  0%|                                                                                                                                                          | 0/1 [00:03<?, ?it/s]
DEBUG - There were 1 kaldi processing files that had errors:

DEBUG - /Users/yvvirkar/Documents/MFA/it_corpus_pretrained_aligner/pretrained_aligner/log/align.0.log
DEBUG -         /Users/yvvirkar/opt/anaconda3/envs/stta/bin/gmm-boost-silence --boost=1.0 1
                 /Users/yvvirkar/Documents/MFA/it_corpus_pretrained_aligner/pretrained_aligner/final.mdl -
DEBUG -         /Users/yvvirkar/opt/anaconda3/envs/stta/bin/gmm-align-compiled --transition-scale=1.0 --acoustic-
                 scale=0.1 --self-loop-scale=0.1 --beam=10 --retry-beam=40 --careful=false -
                 ark:/Users/yvvirkar/Documents/MFA/it_corpus_pretrained_aligner/pretrained_aligner/fsts.1.0.ark
                 'ark,s,cs:apply-cmvn --utt2spk=ark:"/Users/yvvirkar/Documents/MFA/it_corpus_pretrained_aligner/it_corpu
                 s/split1/utt2spk.1.0.scp"
                 scp:"/Users/yvvirkar/Documents/MFA/it_corpus_pretrained_aligner/it_corpus/split1/cmvn.1.0.scp"
                 scp:"/Users/yvvirkar/Documents/MFA/it_corpus_pretrained_aligner/it_corpus/split1/feats.1.0.scp" ark:- |
                 splice-feats --left-context=3 --right-context=3 ark:- ark:- | transform-feats
                 "/Users/yvvirkar/Documents/MFA/it_corpus_pretrained_aligner/pretrained_aligner/lda.mat" ark:- ark:- |'
                 ark:/Users/yvvirkar/Documents/MFA/it_corpus_pretrained_aligner/pretrained_aligner/ali.1.0.ark ark,t:-
DEBUG -         WARNING (gmm-boost-silence[5.5.985]:main():gmmbin/gmm-boost-silence.cc:82) The pdfs for the silence
                 phones may be shared by other phones (note: this probably does not matter.)
DEBUG -         LOG (gmm-boost-silence[5.5.985]:main():gmmbin/gmm-boost-silence.cc:93) Boosted weights for 1 pdfs, by
                 factor of 1
DEBUG -         LOG (gmm-boost-silence[5.5.985]:main():gmmbin/gmm-boost-silence.cc:103) Wrote model to -
DEBUG -         transform-feats /Users/yvvirkar/Documents/MFA/it_corpus_pretrained_aligner/pretrained_aligner/lda.mat
                 ark:- ark:-
DEBUG -         apply-cmvn
                 --utt2spk=ark:/Users/yvvirkar/Documents/MFA/it_corpus_pretrained_aligner/it_corpus/split1/utt2spk.1.0.s
                 cp scp:/Users/yvvirkar/Documents/MFA/it_corpus_pretrained_aligner/it_corpus/split1/cmvn.1.0.scp
                 scp:/Users/yvvirkar/Documents/MFA/it_corpus_pretrained_aligner/it_corpus/split1/feats.1.0.scp ark:-
DEBUG -         splice-feats --left-context=3 --right-context=3 ark:- ark:-
DEBUG -         LOG (apply-cmvn[5.5.985]:main():featbin/apply-cmvn.cc:162) Applied cepstral mean normalization to 1
                 utterances, errors on 0
DEBUG -         LOG (transform-feats[5.5.985]:main():featbin/transform-feats.cc:158) Overall average [pseudo-]logdet is
                 -91.8959 over 1299 frames.
DEBUG -         LOG (transform-feats[5.5.985]:main():featbin/transform-feats.cc:161) Applied transform to 1 utterances;
                 0 had errors.
DEBUG -         LOG (gmm-align-compiled[5.5.985]:main():gmmbin/gmm-align-compiled.cc:127) 1-1
DEBUG -         WARNING (gmm-align-compiled[5.5.985]:AlignUtteranceWrapper():decoder/decoder-wrappers.cc:617) Retrying
                 utterance 1-1 with beam 40
DEBUG -         WARNING (gmm-align-compiled[5.5.985]:AlignUtteranceWrapper():decoder/decoder-wrappers.cc:626) Did not
                 successfully decode file 1-1, len = 1299
DEBUG -         LOG (gmm-align-compiled[5.5.985]:main():gmmbin/gmm-align-compiled.cc:135) Overall log-likelihood per
                 frame is nan over 0 frames.
DEBUG -         LOG (gmm-align-compiled[5.5.985]:main():gmmbin/gmm-align-compiled.cc:137) Retried 1 out of 1 utterances.
DEBUG -         LOG (gmm-align-compiled[5.5.985]:main():gmmbin/gmm-align-compiled.cc:139) Done 0, errors on 1
ERROR - There was an error in the run, please see the log.
KaldiProcessingError:

  There were 1 job(s) with errors when running Kaldi binaries.
  See the log files below for more information.
  /Users/yvvirkar/Documents/MFA/it_corpus_pretrained_aligner/pretrained_aligner/log/align.0.log
   For more details, please check /Users/yvvirkar/Documents/MFA/it_corpus_pretrained_aligner/pretrained_aligner.log

------------------------------------------------------------------------------------------------------------------

I am not sure how to solve this error, but hope this feedback helps. Thanks.
