### ISSUE TITLE
Disable or pass through Kaldi's --dither option for deterministic feature extraction

### ISSUE THREAD

**Issue by arlofaria** [MontrealCorpusTools/Montreal-Forced-Aligner#525]
**Problem**
MFA generates irreproducible output, due to the configuration of feature extraction in Kaldi.  In particular, when applying a dither, the RNG in Kaldi is not seeded deterministically.

**Proposed solution**
The easiest solution is to hardcode Kaldi's `--dither` option to a non-default value of 0.0 to disable dithering.  This may be problematic for features that use energy instead of C0, in which case you'd also want to set some energy floor.  If users really require dithering, they could apply it to the input waveforms themselves, e.g. using `sox` (in which case pass `-R` to ensure reproducibility).

A better solution is to pass through a `dither` configuration variable from MFA, similar to how some feature extraction parameters are used in training mode.  A minor complication is that these parameters do not seem to be passed through for alignment mode, as they are expected to be loaded from a model's JSON configuration.

**Alternative solution**
We could propose a change to Kaldi so that a seed could be set or passed to the `RandState` instantiated for dithering purposes: see [feature-window.cc](https://github.com/kaldi-asr/kaldi/blob/cbed4ff688a172a7f765493d24771c1bd57dcd20/src/feat/feature-window.cc#L95).

**Comment by mmcauliffe** [comment]
For the next version, `dither` along with other feature calculation parameters can get passed through.

**Comment by cassiotbatista** [comment]
Hi guys,

Question for (and from) the lazy: how exactly can one disable dither? 

The param is not listed in the [feat config opts](https://montreal-forced-aligner.readthedocs.io/en/latest/user_guide/configuration/global.html#feature-configuration), but I suppose I should pass a yaml file to `mfa align` via `--config_path` arg, having the following content:

```yaml
dither: 0
```

Right?

**Comment by arlofaria-zoom** [comment]
Oi @cassiotbatista! I think the problem is that the `dither` option is read from the `meta.json` file associated with a pretrained model, and so you'd need to modify that file as packaged for a particular model (e.g. in a ZIP archive).

Hi @mmcauliffe! Alternatively would you be open to a new feature that adds a `--dither` command-line option to `mfa align`?  This would override any dither value that was used to train the model, which might be somewhat mismatched, but at least it enables deterministic behavior.  (For example, it could set `aligner.acoustic_model._meta["features"]["dither"]`, which is a bit of a monkey patch since there's no public setter for the acoustic model's MFCC options.)

Or perhaps are we misunderstanding what you meant by this comment?
> For the next version, dither along with other feature calculation parameters can get passed through.
