### ISSUE TITLE
How to detect high loss alignments from a trained model?

### ISSUE THREAD

**Issue by rbracco** [MontrealCorpusTools/Montreal-Forced-Aligner#569]
**Is your feature request related to a problem? Please describe.**
When training models, a common workflow is to fit a model and then look at the examples the model struggles most with (in both training and holdout data) to learn the models limitations, discover bad labels, and learn how to improve the model further. If I fit a custom acoustic model, is there currently any recommended way to evaluate the accuracy and find the files it struggled with the most (other than just opening lots of audios/textgrids and listening to them)?

**Describe the solution you'd like**
An explanation of how to do this if it already exists (I could also PR it to the documentation if it's undocumented). If it doesn't exist, a command flag on `mfa train` or `mfa align` that would show some type of metric for the overall training, as well as the files it struggled to most to align (if such a thing is possible). I don't know what the internals of the model look like so unfortunately I can't give a detailed suggestion for a solution. I did notice `mfa train_g2p` has an `evaluate` flag that uses different folds for train/valid and then returns some type of accuracy metric.

**Describe alternatives you've considered**
I checked the docs and issues for existing features or discussion.

**Comment by mmcauliffe** [comment]
Yeah, so not internal to MFA, though the information for the utterance loss is stored in the database/exported to the temporary alignment directory in `alignment_log_likelihood.csv`, but both of those are not great for inspecting/fixing problematic examples, especially if you're having to go through praat for each pair.  I have another tool that's built on top of MFA called Anchor that's really geared towards this, which is how I've been fixing up the corpora for the various pretrained models.  Here's a screenshot of a recent-ish build:

![Screenshot 2022-12-02 140507](https://user-images.githubusercontent.com/2791247/219210539-39b46aea-4373-4355-83ab-ba2725e98e24.png)

I'm planning on getting a release out soon for it now that 2.1/2.2 is released and I think I've caught all the major issues (well, or other people have), so I'll have that as my next big priority after I fix some residual things for 2.2.1.  Fair warning though, it'll be kinda rough around the edges and lacking in documentation for a while, but you can load corpora, inspect files, align them using dictionaries/acoustic models, and then sort based on alignment loglikelihood, so that might fit what you need.

**Comment by rbracco** [comment]
That sounds awesome, thank you for all of your work and let me know if you need someone to beta it and provide feedback. The sorting based on alignment log likelihood would be nice. For now I'll peeking inside `alignment_log_likelihood.csv`, thanks for the tip.

**Comment by Eie1** [comment]
Dear mmcauliffe, could  I download mfa Anchor? I want to analyze accuracy of mfa with other tools. 
Thanks very much if you can reply

**Comment by Eie1** [comment]
and have you also can get alignment_analysis.csv？thanks very much if you can reply
