### ISSUE TITLE
[BUG] Alignment duration doesn't match audio duration (0.864s != 0.830s)

### ISSUE THREAD

**Issue by rbracco** [MontrealCorpusTools/Montreal-Forced-Aligner#570]
**Debugging checklist**

[X] Have you updated to latest MFA version?
[X] Have you tried rerunning the command with the `--clean` flag?

**Describe the issue**
Alignment of an audio that is 0.864 seconds long results in a textgrid file that is 0.83 seconds long. I confirmed the length of the audio using soxi, torchaudio, and loading it into audacity, all sources agree that is 13824 samples at a sample rate of 16000 for a duration of 0.864. I tried using `--no-textgrid-cleanup` during the align step in case that was causing it but the textgrid file was still 0.83 seconds. 

Alignment was done with command: `mfa align --clean corpora/test_duration/ english_us_arpa english_us_arpa test_duration_aligned_arpa`

**For Reproducing your issue**

[Google Drive Link to Audio](https://drive.google.com/file/d/1yhmwXiq4ZG843rpXHkpHqH_VsLDVoRtn/view?usp=share_link)
[Google Drive Link to Text](https://drive.google.com/file/d/1EPMfRxi_mWLmM7at4-Cy6PRDp3a_kbp_/view?usp=sharing) (It's just a .txt file with the word "smash" inside)

1. Corpus structure - English, using 16k mp3 and text files
2. Dictionary: english_us_arpa
3. Acoustic model: english_us_arpa
  

**Desktop (please complete the following information):**
Ubuntu 20.04

**Additional context**

**Comment by mmcauliffe** [comment]
I fixed a bug in duration parsing for this, but it results in 0.828 as actual duration coming out of sox. So this is a little tricky, since the sources I've looked at don't agree on the length of it. I'm getting:

* Sox (what MFA uses by default, uses MAD): 13248 samples, 0.828 seconds
* Praat (no idea how it's decoding MP3, it says it's using MAD too, but it's reporting even shorter duration...): 12623 samples, 0.7889375 seconds
* ffmpeg (libav): 13824 samples, 0.864 seconds

I can switch over mp3 processing from sox (which uses MAD to do mp3 deconding) to ffmpeg, but I was finding that ffmpeg/ffprobe was a lot slower than sox for processing lots of files This was a while ago that I benchmarked it, so maybe that's no longer the case, I can look into it more.

**Comment by mmcauliffe** [comment]
Hmm, going from smash.mp3 > `ffmpeg -i smash.mp3 smash_ffmpeg.wav` > `ffmpeg -i smash_ffmpeg.wav smash_ffmpeg.mp3` gives an even different duration, but at least ffmpeg/sox agree that it's 0.93600 (and praat thinks it's 0.8969375), so it might be an option if you want to decode/re-encode to get more consistent durations.

Oh, probably the root of the difference is that ffmpeg reports 24k bit rate, but sox gives 25k.  Do you know what it actually should be?

**Comment by rbracco** [comment]
Thanks for looking into this, looks like it's not an MFA problem then. Also I misread the sox output, you're right that sox disagrees and has 13248 samples, not 13824. 

The decode/re-encode hack is a nice trick, I may try that for my audios that are disagreeing with MFA/praat. I don't know about the actual bitrate of the original audio either. I appreciate the help, looking into it. Closing for now since it's outside the scope of MFA, but let me know if you need me to do any additional testing.
