### ISSUE TITLE
Ability to Input Specific Subfolders Inside of a Corpus Directory Folder

### ISSUE THREAD

**Issue by NataliaShmueli** [MontrealCorpusTools/Montreal-Forced-Aligner#619]
**Is your feature request related to a problem? Please describe.**

_**A feature that would be nice is something similar to how we can use sub-dictionaries would be the ability to link to sub-directories. This could be useful for corpora that are spread out or corpora that are organized by language for cross-lingual alignments without having to change your entire folder structure.**_

**Describe the solution you'd like**

_**Similar to how linking to the .yaml for the sub-dictionaries, maybe a .yaml link to the sub-directory positions would be viable.**_

**Describe alternatives you've considered**

_**I have tested out cross-lingual models which increase alignments for lower resource languages by putting them in the same folder, however, this can take up a large amount of extra space and would be easier if it was simply linkable.**_

**Additional context**

**Comment by mmcauliffe** [comment]
You can use symbolic links in the corpus directory to the folder containing the data elsewhere rather than copying the data over, the corpus parsers follow symbolic links.

See https://learn.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/create-symbolic-links for Windows, https://kb.iu.edu/d/abbe for unix
