### ISSUE TITLE
Why use conda for installation over pip?

### ISSUE THREAD

**Issue by AidanRosen** [MontrealCorpusTools/Montreal-Forced-Aligner#686]
I'm downloading MFA because another repo I'm working on needs it. But, when I download with conda, I can't use the mfa command in my cmd terminal where I run the repo scripts. Why download with conda in the first place over pip?

**Comment by mmcauliffe** [comment]
Did you activate your conda environment? Something like `conda activate aligner` depending on the name you used for creating the environment (see https://montreal-forced-aligner.readthedocs.io/en/latest/installation.html#general-installation).

Conda is used because MFA depends on non-python libraries that would require installation in a conda environment anyway.

**Comment by AidanRosen** [comment]
Ok so what do you recommend I do for my project then - it uses a bash script that needs mfa, like the mfa command (need to add to path somehow) but it doesn't sound like I'll be able to run my project's scripts from the conda terminal

**Comment by mmcauliffe** [comment]
The `conda activate aligner` is just a command that you would run in the terminal before running the bash script.  It's not a separate terminal, it just modifies the paths of the current terminal window.

**Comment by AidanRosen** [comment]
Oh I see, I was opening miniconda terminal then installing. Thanks I'll try that.
