### ISSUE TITLE
Config parameters for best alignment

### ISSUE THREAD

**Issue by cveaux** [MontrealCorpusTools/Montreal-Forced-Aligner#72]
Hi,  just a question about the default values set in `aligner/config.py` especially regarding the mfcc. 

I am trying to optimise the parameters for the alignment and saw that you set `use_energy=False` by default whereas its default value in Kaldi's `compute-mfcc-feats` is True. Is there a special reason why? When I switch it to True the average log-likelihood after running `train_and_align` is better by 5dB although it's hard to judge any improvements on the alignment itself. Moreover I've seen that others also set `use_energy=False` (Eleanor Chodroff's tutorial on alignment with Kaldi for instance). 
Have you made a comparison yourself or do you know the rationale behind this choice?  

P.s: Just a side remark, in the documentation it is said that it's equivalent to use any sampling rates above 16kHz for the audio files. In fact the default preemphasis coefficient (0.97) correspond to a 16kHz sampling so it will be less optimal for higher sampling rates.

**Comment by mmcauliffe** [comment]
Right, so the `use_energy=False` comes from the recipes which use this mfcc.conf: https://github.com/kaldi-asr/kaldi/blob/master/egs/wsj/s5/conf/mfcc.conf.  I haven't done any work on this, though the next release that I'm (slowly) getting ready should make it easier to do these kinds of experiments, since it exposes a lot more configuration options to the user.

And right, good point, preemphasis I guess should vary as a function of the sample rate.  I'll look into that at some point.  I don't think it'll affect alignment too much in the long run, but it'd still be good to do.

**Comment by cveaux** [comment]
Thanks for your reply. I made further tests, and indeed `use_energy=False` yields to much better results. I don't have a reference alignment though so my evaluation metric is the mel-cepstrum distance between the original and predicted spectrum (from a Dnn using the alignment as input).
