### ISSUE TITLE
why results of "mfa align" is texts not phonemes？

### ISSUE THREAD

**Issue by Xwmiss** [MontrealCorpusTools/Montreal-Forced-Aligner#740]
Thanks for your work first！

When I am using mfa to get results from japanese, I find that results in TextGrid is texts, like below:
![image](https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/assets/111272125/23400b30-3ed7-4259-8992-f80fa3fe179d)

While I need is the align results is for the phonemes in the dictionary, like below:
![image](https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/assets/111272125/8f850a84-2313-41fc-ac5f-4a04fcbeef25)

Could you tell me how to fix this?

Thank you again.

**Comment by Xwmiss** [comment]
and in the part2 is only the "spn"
![image](https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/assets/111272125/04b649aa-499f-4ac2-b123-83ba485c0a3c)

**Comment by Daisyqk** [comment]
Have you solved it? I come across the same problem.

**Comment by mmcauliffe** [comment]
If you're using a model before 3.0, you'll have to run tokenization on the corpus first, since Japanese text does not contain spaces typically: https://montreal-forced-aligner.readthedocs.io/en/latest/user_guide/corpus_creation/tokenize.html with https://mfa-models.readthedocs.io/en/latest/tokenizer/Japanese/Japanese%20tokenizer%20v2_2_1.html#Japanese%20tokenizer%20v2_2_1.

If you update to MFA 3.0 and download the latest Japanese models, they use third party tokenizers automatically.

1. `mfa model download acoustic japanese_mfa --ignore_cache`
2. `mfa model download dictionary japanese_mfa --ignore_cache`
3. `conda install -c conda-forge spacy sudachipy sudachidict-core`
4. Re-run the alignment command
