### ISSUE TITLE
New lexicon format support?

### ISSUE THREAD

**Issue by makerjackie** [MontrealCorpusTools/Montreal-Forced-Aligner#75]
if I want to use a different lexicon format like
```
AAT AAT
AB  AEB
AB  AB
```
instead of 
```
AAT AA1 T
AB  AE1 B
AB  EY1 B IY1
```
where I should change the code?

**Comment by mmcauliffe** [comment]
That happens here: https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/blob/master/aligner/dictionary.py#L120

Although you will likely run into issues not using a space-delimited transcription, unless you have a 1-to-1 correspondence between characters and phones.  Namely in the first word, should the resulting phones be `'AA', 'T'` or `'A', 'A', 'T'`?  Without someway of delimiting or knowing the inventory ahead of time, it'll be harder to actually split the transcription into separate phones for alignment.

**Comment by mmcauliffe** [comment]
From your other issue:

```
liang3 l iang3
```
would probably be better aligned as
```
liang3 l ia3 ng
```

Since `ng` is digraph for a single phone, and `ia` a diphthong (I would think).  Tone is often marked on the vowel rather than the coda, as well.

You might also want to look at the pinyin G2P model that should generate a properly formatted dictionary from pinyin already, I believe in the second format above, though it's been a while since I used it.  See the G2P model here: http://montreal-forced-aligner.readthedocs.io/en/latest/pretrained_models.html#pretrained-g2p-models, and http://montreal-forced-aligner.readthedocs.io/en/latest/dictionary_generating.html for how to use it to generate a dictionary.

**Comment by Jackiexiao** [comment]
I have already tested `liang3 l iang3` and `liang3 l ia3 ng`, so I wonder could I just regard pinyin `liang3` a single phone without splitting it into several phones, could it produce better alignment? I just need word alignment.
